---
title: "Assignment_1_Yosuf"
output: html_document
---

```{r}
# Set Session Options
options(
  digits = 6, # Significant figures output
  scipen = 999, # Disable scientific notation
  repos = getOption("repos")["CRAN"] # Install packages from CRAN
)

# Set the makeflags to use multiple cores for faster compilation
Sys.setenv(
  MAKEFLAGS = paste0(
    "-j", 
    parallel::detectCores(logical = FALSE)
    ))
```
```{r}
library(tidyverse)
```

```{r}
pacman::p_load(furrr, parallel)
```

```{r}
n_cores<-parallel::detectCores()-2
plan(multisession, workers = n_cores )
```


```{r}
trials = 500
Self = rep(NA, trials)
Other = rep(NA, trials)
memory = rep(NA,trials)
result = rep(NA,trials)
V = rep(NA,trials)

RandomAgent = function(rate){
  choice = rbinom(1,1,rate)
  return(choice)
}


WSLSAgent_f=function(prevChoice, feedback){
  if(feedback == 1){
    choice = prevChoice
  }
  else if (feedback == 0) {
    choice = 1 -prevChoice 
  }
return(choice) 
}


InfiniteMemoryAgent= function(count, prevChoice, feedback){
  if(feedback == 0)
  {
    newChoice = 1 - prevChoice
  }
  else{
    newChoice = prevChoice
  }
  memory[count] = newChoice
  EV = sum(memory,na.rm = TRUE) / count
  choice = rbinom(1,1,EV)
  # Learning rate
  return(choice)
}

RLAgent = function(count, alpha, feedback){
  V[count] <<- (V[count-1] + alpha*(feedback - V[count-1]))
  choice = rbinom(1,1,V[count])
  return(choice)
}
```

```{r}
learning_rate = 0.2
rate = 0.7
Self[1] = RandomAgent(0.5)
V[1] = 0.5

```

```{r}

for(t in seq (trials)){
  Other[t] = RandomAgent(rate)
}

result[1] = if(Self[1]==Other[1]){feedback = 1}else{feedback = 0}

for(i in 2:trials){
  if(Self[i-1] == Other[i-1]){
    feedback = 1
  }
  else{
    feedback = 0
  }
  Self[i] = RLAgent(i, learning_rate, feedback)
  result[i] = feedback
  }
```

```{r}
print("----SELF----")
print(Self)
print("----OTHER----")
print(Other)
print("----V----")
print(V)
print("----RESULT----")
print(result)
```
```{r}
df = tibble(Self, Other, trial = seq(trials), Feedback = as.numeric(Self==Other))

ggplot(df) + theme_classic() + geom_line(color ="red", aes(trial, Self),size = 1) + geom_line(color ="blue", aes(trial, Other),size = 1)+ geom_line(color="green", aes(trial,V), size = 1.5) + geom_hline(yintercept=rate, size = 1.5)  + ggtitle("RLAgent(red) vs BiasedAgent(blue) + Expected Value(green)") + ylab("Choices 1/0")
```
```{r}
df = df %>% mutate(expected_value = V)
head(df)
```

```{r}
df <- df %>% mutate( cumulative_rateSelf = cumsum(Feedback) / seq_along(Feedback), cumulative_rateOther = cumsum(1 - Feedback)/seq_along(Feedback) )
ggplot(df) + theme_classic() + geom_line (color ="red", aes (trial, cumulative_rateSelf )) + geom_line(color ="blue", aes (trial, cumulative_rateOther)) 

ggplot(df) + theme_classic() + geom_line (color ="red", aes (trial, Self)) + geom_line(color ="blue", aes (trial, Other)) 

```
```{r}

```




